# Generated by Django 5.1.3 on 2025-02-19 14:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Actividad Económica')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'actividad económica',
                'verbose_name_plural': 'actividades económicas',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estdo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='INCOTERMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelofacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('secuencia', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OtrosDicumentosAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_dte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDomicilioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGeneracionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInvalidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRetencionIVAMH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDocIDReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEstablecimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiposServicio_Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Emisor_fe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT del Emisor')),
                ('nrc', models.CharField(max_length=50, null=True)),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('direccion_comercial', models.TextField(verbose_name='Dirección Comercial')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('codigo_establecimiento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Establecimiento')),
                ('codigo_punto_venta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo de Punto de Venta')),
                ('actividades_economicas', models.ManyToManyField(to='dte.actividadeconomica', verbose_name='Actividades Económicas')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.municipio')),
                ('tipoestablecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tiposestablecimientos')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.pais'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('preunitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('tiene_descuento', models.BooleanField(default=False)),
                ('descuento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Receptor_fe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nrc', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('actividades_economicas', models.ManyToManyField(to='dte.actividadeconomica', verbose_name='Actividades Económicas')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.municipio')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tiposdocidreceptor')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('numero_control', models.CharField(blank=True, max_length=31, unique=True)),
                ('codigo_generacion', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('motivocontin', models.CharField(max_length=350, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('total_no_sujetas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_exentas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_gravadas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sub_total_ventas', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('descuen_no_sujeto', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('descuento_exento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('descuento_gravado', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('por_descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iva_retenido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('retencion_renta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_operaciones', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_no_gravado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_letras', models.CharField(max_length=250, null=True)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('json_original', models.JSONField()),
                ('json_firmado', models.JSONField(blank=True, null=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ambiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.ambiente')),
                ('condicion_operacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.condicionoperacion')),
                ('dteemisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_emisor_FE', to='dte.emisor_fe')),
                ('tipomodelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.modelofacturacion')),
                ('dtereceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_receptor_FE', to='dte.receptor_fe')),
                ('tipo_dte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tipo_dte')),
                ('tipocontingencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontingencia')),
                ('tipomoneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tipomoneda')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto')),
                ('iva_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado (en monto) sobre el total sin IVA', max_digits=5)),
                ('ventas_no_sujetas', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ventas_exentas', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ventas_gravadas', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pre_sug_venta', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('no_gravado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('factura', models.ForeignKey(help_text='Factura a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='dte.facturaelectronica')),
                ('producto', models.ForeignKey(help_text='Producto asociado a este detalle', on_delete=django.db.models.deletion.CASCADE, to='dte.producto')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tipounidadmedida')),
            ],
        ),
    ]
