# Generated by Django 5.1.3 on 2025-02-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='ambiente',
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='ambiene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.ambiente'),
            preserve_default=False,
        ),
    ]
