# Generated by Django 5.1.3 on 2024-11-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta_pago',
            old_name='hr_extra_di',
            new_name='biaticos',
        ),
        migrations.RenameField(
            model_name='boleta_pago',
            old_name='hr_extra_noc',
            new_name='comisiones',
        ),
    ]
