# Generated by Django 5.1.3 on 2024-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0003_rename_biaticos_boleta_pago_viaticos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta_pago',
            name='comisiones',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='descuento_afp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='descuento_isss',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='descuento_renta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='dias_laborados',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='hr_extra_fer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='hr_extra_fer_noc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='liquido_recibir',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='otro_descuento1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='otro_descuento2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='total_descuentos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta_pago',
            name='viaticos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
