# Generated by Django 5.1.3 on 2024-12-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=20)),
                ('nrc', models.CharField(max_length=20)),
                ('telefono_empresa', models.CharField(max_length=20)),
                ('correo_empresa', models.EmailField(max_length=100)),
                ('direccion_empresa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quedan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quedan', models.CharField(max_length=20)),
                ('fecha_entrega', models.DateField()),
                ('comentario_quedan', models.CharField(max_length=100)),
                ('cant_facturas', models.IntegerField()),
                ('estado_enviado', models.BooleanField(default=True)),
                ('ultima_fecha_pago', models.DateField()),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, default=None, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='facturas_quedan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=10)),
                ('num_doc', models.CharField(max_length=20)),
                ('fecha_doc', models.DateField()),
                ('suma_efect', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_ret_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_percep', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.proveedor')),
                ('quedan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.quedan')),
            ],
        ),
        migrations.CreateModel(
            name='quedan_pago_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pago', models.BooleanField(default=True)),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quedan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.quedan')),
            ],
        ),
    ]
