# Generated by Django 5.1.3 on 2024-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0002_proveedor_codigo_proveedor_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
