# Generated by Django 5.1.3 on 2024-12-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0004_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo_empresa',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nrc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_empresa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
