# Generated by Django 5.1.3 on 2024-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0005_alter_proveedor_correo_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_empresa',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_empresa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='giro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nrc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_empresa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
