# Generated by Django 5.1.3 on 2024-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0006_alter_proveedor_apellido_alter_proveedor_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
