# Generated by Django 5.1.3 on 2024-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0007_alter_proveedor_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quedan',
            name='estado_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
