# Generated by Django 5.1.3 on 2024-12-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0008_alter_quedan_estado_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quedan',
            name='comentario_quedan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
