# Generated by Django 5.1.3 on 2024-12-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0009_alter_quedan_comentario_quedan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas_quedan',
            name='num_doc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facturas_quedan',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facturas_quedan',
            name='porcentaje_percep',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facturas_quedan',
            name='porcentaje_ret_iva',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facturas_quedan',
            name='suma_efect',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='facturas_quedan',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
