# Generated by Django 5.1.3 on 2024-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(max_length=31, unique=True)),
                ('codigo_generacion', models.CharField(max_length=36, unique=True)),
                ('nit_emisor', models.CharField(max_length=14)),
                ('nombre_emisor', models.CharField(max_length=250)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField()),
                ('hora_emision', models.TimeField()),
                ('receptor_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('receptor_nit', models.CharField(blank=True, max_length=14, null=True)),
                ('detalles', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/pdf/')),
                ('archivo_json', models.FileField(blank=True, null=True, upload_to='documentos/json/')),
            ],
        ),
    ]
