# Generated by Django 5.1.3 on 2025-02-06 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_data',
            name='activado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='token_data',
            name='fecha_cducidad',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
