# Generated by Django 5.1.3 on 2025-02-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0002_token_data_activado_token_data_fecha_cducidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token_data',
            old_name='fecha_cducidad',
            new_name='fecha_caducidad',
        ),
    ]
