# Generated by Django 5.1.3 on 2025-02-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0004_facturaelectronica_numerocontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Actividad Económica')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'actividad económica',
                'verbose_name_plural': 'actividades económicas',
            },
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT del Emisor')),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('direccion_comercial', models.TextField(verbose_name='Dirección Comercial')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('codigo_establecimiento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Establecimiento')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('actividades_economicas', models.ManyToManyField(to='FE.actividadeconomica', verbose_name='Actividades Económicas')),
            ],
            options={
                'verbose_name': 'emisor',
                'verbose_name_plural': 'emisores',
            },
        ),
    ]
