# Generated by Django 5.1.3 on 2025-02-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0005_actividadeconomica_emisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomica',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código de Actividad Económica'),
        ),
    ]
