# Generated by Django 5.1.3 on 2025-02-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0006_alter_actividadeconomica_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptor_fe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('36', 'DUI'), ('13', 'NIT')], max_length=2, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nrc', models.CharField(blank=True, max_length=8, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Emisor',
            new_name='Emisor_fe',
        ),
        migrations.AlterModelOptions(
            name='emisor_fe',
            options={},
        ),
    ]
