# Generated by Django 5.1.3 on 2025-02-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0008_facturaelectronica_dteemisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='dtereceptor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_receptor_FE', to='FE.receptor_fe'),
            preserve_default=False,
        ),
    ]
