# Generated by Django 5.1.3 on 2025-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0009_facturaelectronica_dtereceptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_data',
            name='password_privado',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
