# Generated by Django 5.1.3 on 2025-02-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0010_token_data_password_privado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_dte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='codigo_punto_venta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo de Punto de Venta'),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='nrc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.departamento'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='Departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.departamento'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='municipio',
            field=models.ManyToManyField(to='FE.municipio', verbose_name='Municipios'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipo_dte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipo_dte'),
        ),
    ]
