# Generated by Django 5.1.3 on 2025-02-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0011_departamento_municipio_tipo_dte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisor_fe',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='receptor_fe',
            name='Departamento',
        ),
        migrations.AddField(
            model_name='emisor_fe',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.municipio'),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.municipio'),
        ),
    ]
