# Generated by Django 5.1.3 on 2025-02-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0014_modelofacturacion_tipocontingencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='municipio',
        ),
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FE.departamento'),
            preserve_default=False,
        ),
    ]
