# Generated by Django 5.1.3 on 2025-02-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0015_remove_departamento_municipio_municipio_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricpion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
