# Generated by Django 5.1.3 on 2025-02-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0016_condicionoperacion_formaspago_plazo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formaspago',
            old_name='descricpion',
            new_name='descripcion',
        ),
    ]
