# Generated by Django 5.1.3 on 2025-02-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0018_incoterms_otrosdicumentosasociado_pais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptor_fe',
            name='tipo_documento',
        ),
    ]
