# Generated by Django 5.1.3 on 2025-02-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0019_remove_receptor_fe_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor_fe',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('36', 'DUI'), ('13', 'NIT')], max_length=2, null=True),
        ),
    ]
