# Generated by Django 5.1.3 on 2025-02-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0022_descuento_emisor_fe_tipoestablecimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='exentas',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='gravadas',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='no_sujetas',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado (en monto) sobre el total sin IVA', max_digits=5)),
                ('total_sin_iva', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total sin IVA (cantidad * precio_unitario - descuento)', max_digits=10)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='IVA calculado (por ejemplo, 13% sobre el total sin IVA)', max_digits=10)),
                ('total_con_iva', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Total con IVA (total_sin_iva + iva)', max_digits=10)),
                ('factura', models.ForeignKey(help_text='Factura a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='FE.facturaelectronica')),
                ('producto', models.ForeignKey(help_text='Producto asociado a este detalle', on_delete=django.db.models.deletion.CASCADE, to='FE.producto')),
            ],
        ),
    ]
