# Generated by Django 5.1.3 on 2025-02-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0023_remove_facturaelectronica_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='iva_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
