# Generated by Django 5.1.3 on 2025-02-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0024_detallefactura_iva_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='facturaelectronica',
            old_name='tipooperacion',
            new_name='condicion_operacion',
        ),
        migrations.RenameField(
            model_name='facturaelectronica',
            old_name='iva_percibido',
            new_name='total_iva',
        ),
        migrations.RenameField(
            model_name='facturaelectronica',
            old_name='sum_total_operaciones',
            new_name='total_no_gravado',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='total_con_iva',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='total_sin_iva',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='suma_exentas',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='suma_gravadas',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='suma_no_sujetas',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='sumas',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='no_gravado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='pre_sug_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='ventas_exentas',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='ventas_gravadas',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='ventas_no_sujetas',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='descuen_no_sujeto',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='descuento_exento',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='descuento_gravado',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='motivocontin',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='por_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='sub_total_ventas',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipocontingencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipocontingencia'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_exentas',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_no_sujetas',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='receptor_fe',
            name='actividades_economicas',
            field=models.ManyToManyField(to='FE.actividadeconomica', verbose_name='Actividades Económicas'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='iva_item',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='IVA calculado (por ejemplo, 13% sobre el total sin IVA)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='total_gravadas',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipomoneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipomoneda'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FE.tipounidadmedida'),
        ),
    ]
