# Generated by Django 5.1.3 on 2025-02-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0025_tipomoneda_tipounidadmedida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='unidad_medida',
        ),
    ]
