# Generated by Django 5.1.3 on 2025-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0027_detallefactura_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='iva_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
