# Generated by Django 5.1.3 on 2025-02-19 14:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0028_alter_detallefactura_iva_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='iva_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
