# Generated by Django 5.1.3 on 2025-02-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0029_alter_detallefactura_iva_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='iva_item',
        ),
    ]
