# Generated by Django 5.1.3 on 2025-02-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FE', '0032_remove_facturaelectronica_ambiente_emisor_fe_ambiene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emisor_fe',
            old_name='ambiene',
            new_name='ambiente',
        ),
    ]
